controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
jardin:
    path: /jardin
    controller: App\Controller\IndexController::indexJardin
