<?php

namespace ContainerLtc3IA1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2GXVdblService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2GXVdbl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2GXVdbl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EventController::add' => ['privates', '.service_locator.cg5DUby', 'get_ServiceLocator_Cg5DUbyService', true],
            'App\\Controller\\EventController::adminEditParticipant' => ['privates', '.service_locator.Jwhh4jY', 'get_ServiceLocator_Jwhh4jYService', true],
            'App\\Controller\\EventController::affiche' => ['privates', '.service_locator.VWzgfqt', 'get_ServiceLocator_VWzgfqtService', true],
            'App\\Controller\\EventController::afficheEventAdmin' => ['privates', '.service_locator.VWzgfqt', 'get_ServiceLocator_VWzgfqtService', true],
            'App\\Controller\\EventController::delete' => ['privates', '.service_locator.Jwhh4jY', 'get_ServiceLocator_Jwhh4jYService', true],
            'App\\Controller\\EventController::details' => ['privates', '.service_locator.VWzgfqt', 'get_ServiceLocator_VWzgfqtService', true],
            'App\\Controller\\ParticipantController::add' => ['privates', '.service_locator.zg4jnmw', 'get_ServiceLocator_Zg4jnmwService', true],
            'App\\Controller\\ParticipantController::adminAdd' => ['privates', '.service_locator.cg5DUby', 'get_ServiceLocator_Cg5DUbyService', true],
            'App\\Controller\\ParticipantController::adminEditParticipant' => ['privates', '.service_locator.54zNldR', 'get_ServiceLocator_54zNldRService', true],
            'App\\Controller\\ParticipantController::afficherParticipant' => ['privates', '.service_locator.VWzgfqt', 'get_ServiceLocator_VWzgfqtService', true],
            'App\\Controller\\ParticipantController::delete' => ['privates', '.service_locator.54zNldR', 'get_ServiceLocator_54zNldRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\EventController:add' => ['privates', '.service_locator.cg5DUby', 'get_ServiceLocator_Cg5DUbyService', true],
            'App\\Controller\\EventController:adminEditParticipant' => ['privates', '.service_locator.Jwhh4jY', 'get_ServiceLocator_Jwhh4jYService', true],
            'App\\Controller\\EventController:affiche' => ['privates', '.service_locator.VWzgfqt', 'get_ServiceLocator_VWzgfqtService', true],
            'App\\Controller\\EventController:afficheEventAdmin' => ['privates', '.service_locator.VWzgfqt', 'get_ServiceLocator_VWzgfqtService', true],
            'App\\Controller\\EventController:delete' => ['privates', '.service_locator.Jwhh4jY', 'get_ServiceLocator_Jwhh4jYService', true],
            'App\\Controller\\EventController:details' => ['privates', '.service_locator.VWzgfqt', 'get_ServiceLocator_VWzgfqtService', true],
            'App\\Controller\\ParticipantController:add' => ['privates', '.service_locator.zg4jnmw', 'get_ServiceLocator_Zg4jnmwService', true],
            'App\\Controller\\ParticipantController:adminAdd' => ['privates', '.service_locator.cg5DUby', 'get_ServiceLocator_Cg5DUbyService', true],
            'App\\Controller\\ParticipantController:adminEditParticipant' => ['privates', '.service_locator.54zNldR', 'get_ServiceLocator_54zNldRService', true],
            'App\\Controller\\ParticipantController:afficherParticipant' => ['privates', '.service_locator.VWzgfqt', 'get_ServiceLocator_VWzgfqtService', true],
            'App\\Controller\\ParticipantController:delete' => ['privates', '.service_locator.54zNldR', 'get_ServiceLocator_54zNldRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\EventController::add' => '?',
            'App\\Controller\\EventController::adminEditParticipant' => '?',
            'App\\Controller\\EventController::affiche' => '?',
            'App\\Controller\\EventController::afficheEventAdmin' => '?',
            'App\\Controller\\EventController::delete' => '?',
            'App\\Controller\\EventController::details' => '?',
            'App\\Controller\\ParticipantController::add' => '?',
            'App\\Controller\\ParticipantController::adminAdd' => '?',
            'App\\Controller\\ParticipantController::adminEditParticipant' => '?',
            'App\\Controller\\ParticipantController::afficherParticipant' => '?',
            'App\\Controller\\ParticipantController::delete' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EventController:add' => '?',
            'App\\Controller\\EventController:adminEditParticipant' => '?',
            'App\\Controller\\EventController:affiche' => '?',
            'App\\Controller\\EventController:afficheEventAdmin' => '?',
            'App\\Controller\\EventController:delete' => '?',
            'App\\Controller\\EventController:details' => '?',
            'App\\Controller\\ParticipantController:add' => '?',
            'App\\Controller\\ParticipantController:adminAdd' => '?',
            'App\\Controller\\ParticipantController:adminEditParticipant' => '?',
            'App\\Controller\\ParticipantController:afficherParticipant' => '?',
            'App\\Controller\\ParticipantController:delete' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
